print(5, 10, "\n7", "sm")
t = int(input("write any number: "))
v = int(input("write any number(one more): "))
x = int(input("write any number for x: "))
y = int(input("write any number for y: "))
print(100, t)
print(1949, v)
print("-----------------------------")
print(x, 25)
print(x, y)
